shareit-add-controllers-FP14
i2GR/java-shareit pull request #1
Opened 2023-04-03 19:56 UTC by i2GR

review 0

2023-04-04 08:13 UTC, AnastasiyaFomkina requested changes
Привет! Ты очень усложнил работу. Давай уберем все лишние абстракции, они делают работу критически сложной для понимания и не дают сильного увеличения масштабируемости

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/Identifiable.java
> +public interface Identifiable {
Интерфейс лишний, мы генерим `id` и сеттеры/геттеры с помощью `lombok`. Нужно удалить

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/IdentifiableDto.java
> +public interface IdentifiableDto extends Identifiable {
Лишнее усложнение. Нужно удалить

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +public abstract class InMemoryStorage<T extends Identifiable> implements Repository<T> {
Лишние абстракции приводят к усложнению кода. Нужно оставить один интерфейс и не перегружать и без того сложный проект

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +    private <C> C invokeGetFieldMethod(T entity, Field field, Class<C> to) {
Не уверена, что этот класс вообще нужен, он не дает никаких плюсов, но вызывает много вопросов

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/CommonExceptionHandler.java
> +        List<ErrorResponse> errors = new ArrayList<>();
А точно ли нужен данный список?

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    @Getter
Лучше вынести над классом

2023-04-04 08:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto postItem(@RequestHeader(value = "X-Sharer-User-Id") Long ownerId, @RequestBody @Valid ItemDto dto) {
`"X-Sharer-User-Id"` нам еще потребуется во многих местах, давай вынесем в отдельный класс и сделаем публичной константой

2023-04-04 08:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return !query.isBlank() ?
Метод с поиском - это бизнес-логика, нужно вынести ее в сервис

2023-04-04 08:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return ItemDtoMapper.INSTANCE.toDto(itemService.deleteById(ownerId, itemId)).getId().equals(itemId)
Приведение к dto и сравнение - бизнес-логика, должна находится на сервисном уровне. Такая же проблема и в методах выше. Поправь, пожалуйста.

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    @Mapping(target = "available", source = "available")
Явно объявлять поля с одинаковыми названия - не нужно. Давай, удалим

2023-04-04 08:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    ItemDtoMapper INSTANCE = Mappers.getMapper(ItemDtoMapper.class);
Лучше подключать, как обычный бин с помощью `dependency injection`

2023-04-04 08:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +                T storedEntity = (T) idService.updateEntityWithId(entity, newId);
Здесь можем поймать [ClassCastException](https://docs.oracle.com/javase/7/docs/api/java/lang/ClassCastException.html)

2023-04-04 08:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +        //return updateWithUniqueValueConstraintCheck(id, entity);
Нужно удалять закомментированный код

2023-04-04 10:53 UTC, i2GR commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
для DTO классов исправлено как сочетание аннотации @Getter над классом и @Setter над полем id
создание экземпляров - через Builder. setX методы же не используются для DTO

2023-04-04 10:54 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/IdentifiableDto.java
> +public interface IdentifiableDto extends Identifiable {
исправлено

2023-04-04 12:22 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/Identifiable.java
> +public interface Identifiable {
Хотел бы обсудить.
Identifiable - чисто контракт.

Для хранения в памяти Identifiable очень удобен тем, что позволяет иметь одно абстрактное хранилище (реализация через HashMap<Long, T extends Identifiable>, в котором определены основные CRUD-методы, и которое подходит для всех сохраняемых сущностей. В этом ТЗ только User и Item.
С таким подходом лдя In-Memory хранения можно избежать повторения кода, когда в разных классах хранилища был один и тот же код по записи id. Только Класс параметра аргумента бы отличался
```
update(User user, newId) <==> update(Item item, newId)
```
Конечно всего 5-6 строчек, но кажется это все равно не DRY-ово :)
А чтобы это сделать, и потребовалось, чтобы User и Item применяли интерфейс Identifiable

Далее, если User и Item не Identifiable. То не получается использовать InMemoryStorage<T>,а нужны отдельные классы InMemoryStoragUser, InMemoryStorageItem, которые только классом параметра аргумента отличаются. и надо дублировать практически полностью коды. 200 дублирующихся строк.

не то чтобы лениво, но лично по мне - кажется нерационально.
Текущее ТЗ позволяет так сделать, получив, некую на мой взгляд, DRY-оптимизацию.
 А InMemory-хранилища, наверное, никак не пригодятся для следующих спринтов.
По хорошему их надо будет вообще удалять - идентификаторы приходить будут из БД.
И тогда уже и можно легко избавиться от интерфейса в объявлении классов.

2023-04-04 12:48 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +public abstract class InMemoryStorage<T extends Identifiable> implements Repository<T> {
первоначальная диаграмма
![classes_13-0](https://user-images.githubusercontent.com/112017515/229795887-97020ab1-80e1-48f2-b745-155007ba0099.png)
Наследование InMemoryStorage<T> -> Repository<T>  - это был контракт
можно удалить лишнее наследование (**центральная линия наследования**)":
![classes_13-1](https://user-images.githubusercontent.com/112017515/229796246-9f5c3b37-e824-44fb-b58a-0a00e6b52b3d.png)
чтобы ,когда InMemory-хранилище будет не нужно в следующих спринтах, получилась ровная структура, расширяемая на все сущности:
![classes_13+](https://user-images.githubusercontent.com/112017515/229796509-dd1bbc0c-9f12-4461-983b-f646c781f750.png)

2023-04-04 12:51 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +    private <C> C invokeGetFieldMethod(T entity, Field field, Class<C> to) {
... постарался описать свою позицию в первом комментарии
все завязано на временной реализации с хранением в памяти

2023-04-04 13:47 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/Identifiable.java
> +public interface Identifiable {
Я все равно не вижу смысла в `getId` и `setId` с учетом того, что мы их генерим для каждой из сущностей, как в данной реализации, так и в реализации с бд. Хочешь быть DRY - создай абстрактный базовый класс, который будет генерить тебе id, а не интерфейс с методами, которые генерит библиотека

2023-04-04 13:50 UTC, afomkina commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +public abstract class InMemoryStorage<T extends Identifiable> implements Repository<T> {
Окей, оставляй, как хочешь.

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/exception/CommonExceptionHandler.java
> +        List<ErrorResponse> errors = new ArrayList<>();
я бы сказал что да.
если в качестве dto отправить пустой json ```{}``` получим полный список ошибок валидации.
```
[
    {
        "error": "Invalid request body",
        "description": "see list"
    },
    {
        "error": "error in field: email",
        "description": "bad value: Email cannot be null"
    },
    {
        "error": "error in field: name",
        "description": "bad value: не должно равняться null"
    },
    {
        "error": "error in field: name",
        "description": "bad value: name cannot be empty"
    },
    {
        "error": "error in field: email",
        "description": "bad value: Email cannot be empty"
    }
][
    {
        "error": "error",
        "description": "Invalid request body"
    },
    {
        "error": "error in field: email",
        "description": "bad value: Email cannot be null"
    },
    {
        "error": "error in field: name",
        "description": "bad value: не должно равняться null"
    },
    {
        "error": "error in field: name",
        "description": "bad value: name cannot be empty"
    },
    {
        "error": "error in field: email",
        "description": "bad value: Email cannot be empty"
    }
]
```

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    @Getter
исправлено

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto postItem(@RequestHeader(value = "X-Sharer-User-Id") Long ownerId, @RequestBody @Valid ItemDto dto) {
вынесено в класс util.Constants статической константой

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return !query.isBlank() ?
вынесено

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return ItemDtoMapper.INSTANCE.toDto(itemService.deleteById(ownerId, itemId)).getId().equals(itemId)
приведено
забавно... на QA ,кстати упомянули, что локация приведения к dto - холиварная тема (очередная :D)

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    @Mapping(target = "available", source = "available")
недоучил...удалил

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    ItemDtoMapper INSTANCE = Mappers.getMapper(ItemDtoMapper.class);
насколько я понял из документации, только же через параметр componentModel или  pom.xml
https://mapstruct.org/documentation/stable/reference/html/#retrieving-mapper

2023-04-04 22:47 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +                T storedEntity = (T) idService.updateEntityWithId(entity, newId);
исправлено

2023-04-04 22:48 UTC, i2GR commented on src/main/java/ru/practicum/shareit/util/inmemory/InMemoryStorage.java
> +        //return updateWithUniqueValueConstraintCheck(id, entity);
my bad:)

2023-04-05 11:01 UTC, AnastasiyaFomkina requested changes
Осталось совсем чуть-чуть

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingDtoMapper.java
> +    BookingDtoMapper INSTANCE = Mappers.getMapper(BookingDtoMapper.class);
Нужно инжектить с помощью dependency injection, как и все другие бины в проекте

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Нужно избавиться `@Data` в проекте в соответствии с данной статьей [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/exception/CommonExceptionHandler.java
> +        List<ErrorResponse> errors = new ArrayList<>();
А зачем нам нужен именно список ошибок? Если твоим приложением будет пользоваться другое приложение, как оно поймет, что конкретно пошло не так? Каким образом ему нужно будет распарсить список ошибок, чтобы понять, что не нужно передавать пустое body?

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto postItem(@RequestHeader(value = "X-Sharer-User-Id") Long ownerId, @RequestBody @Valid ItemDto dto) {
```suggestion
    public ItemDto postItem(@RequestHeader(value = SHARER_USER_HTTP_HEADER) Long ownerId, @RequestBody @Valid ItemDto dto) {
```

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    ItemDtoMapper INSTANCE = Mappers.getMapper(ItemDtoMapper.class);
Когда ты обозначаешь в настройках маппера `componentModel = "spring"`, то маппер автоматически гененируется с аннотацией `@Component`, соответственно, чтобы подлючить его в сервис, нужно просто объявить данный бин:
`private final ItemDtoMapper itemDtoMapper;`
 внутри другого бина и можно будет использовать его для вызова методов без статического доспута:
`Item item = itemMapper.fromDto(dto);`

Поправь для всех мапперов, пожалуйста

2023-04-05 11:01 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemDtoMapper.java
> +    ItemDtoMapper INSTANCE = Mappers.getMapper(ItemDtoMapper.class);
Кстати, чтобы посмотреть сгененированный код маппера, нужно сбилдить приложение с помощью maven и зайти в папку `target/generated-sources/annotations/ru/practicum/shareit`

2023-04-05 20:16 UTC, i2GR commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
странно, заменял... исправлено

2023-04-05 20:16 UTC, i2GR commented on src/main/java/ru/practicum/shareit/booking/BookingDtoMapper.java
> +    BookingDtoMapper INSTANCE = Mappers.getMapper(BookingDtoMapper.class);
наконец то понял...

2023-04-06 10:09 UTC, AnastasiyaFomkina approved these changes

2023-04-15 12:50 UTC, merged