Add item requests
i2GR/java-shareit pull request #3
Opened 2023-05-06 20:54 UTC by i2GR

2023-05-07 07:59 UTC, i2GR commented
небольшая проблема с проверкой json на время
работает, но некрасиво. надо подумать во время ревью...

2023-05-08 08:16 UTC, AnastasiyaFomkina requested changes
Молодец, что написал так много развернутых тестов

2023-05-08 08:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    throw new NotFoundException(format("item-request with id %d not found", requestId));
Так как здесь блок кода, а не просто лямбда выражение, лучше делать 
```suggestion
                    return new NotFoundException(format("item-request with id %d not found", requestId));
```
На уровне выше в `()->` перехватится возвращаемая ошибка и выбросится наружу

2023-05-08 08:16 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    throw new NotFoundException(format("user with id %d not found", userId));
```suggestion
                    return new NotFoundException(format("user with id %d not found", userId));
```

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +    private Item item = Item.builder().id(1L).ownerId(1L).name("item").description("description").available(true).build();
Поля 16-17 можно сделать `final`

2023-05-08 08:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        // Без StdDateFormat даты сериализуются в json так, что если последние милли/нано-секунды это нули(нуль), то это отбрасывается.
Можно попробовать явно указать паттерн строки для парсинга через [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates), таким образом можно избежать проблем при парсинге даты из строки в объект. 
Даже не можно, а точно стоит добавить для полей с датами или настроить Jackson's ObjectMapper, как в статье выше

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private void setupEntityDtos(LocalDateTime start, LocalDateTime end) {
Можно убрать параметры метода, так как они везде одинаковые

2023-05-08 08:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                .start(start)
Соответственно здесь и ниже будет
```suggestion
                .start(BookingServiceImplTest.DEFAULT_START_DATE)
```

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                .end(end)
А для end здесь и ниже будет
```suggestion
                .end(BookingServiceImplTest.DEFAULT_END_DATE)
```

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTestWithMock.java
> +    private BookingResponseDto response1Dto, response2Dto;
Переменные user1, booking2Dto, response2Dto лучше сделать переменными методов

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTestWithMock.java
> +    private void setupEntityDtos(LocalDateTime start, LocalDateTime end) {
Здесь тоже можно отказаться от параметров метода

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemResponseDtoMapperTest.java
> +    private Booking booking;
Можно сконвертировать в переменную метода

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    private ItemResponseDto response1Dto;
Не используется, нужно удалить

2023-05-08 08:16 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +    private final Long requestByUser2Id = 1L;
`1L` -  не стоит дублировать несколько раз с одинаковым названием. Нужно обозначить один раз и придумать более общение название переменной

2023-05-09 08:18 UTC, i2GR commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    throw new NotFoundException(format("item-request with id %d not found", requestId));
если я правильно понял - это нужно сделать для всех orElseThrow в коде.. т.к. это будет соответствовать интерфейсу Supplier<Supplier<? extends X>, где X extends Throwable

2023-05-09 08:18 UTC, i2GR commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    throw new NotFoundException(format("user with id %d not found", userId));
аналогично?..

2023-05-09 08:20 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +    private Item item = Item.builder().id(1L).ownerId(1L).name("item").description("description").available(true).build();
... окэ-й...

2023-05-09 08:24 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                .end(end)
да, действительно...спасибо

2023-05-09 08:24 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                .start(start)
да, действительно...спасибо

2023-05-09 08:24 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private void setupEntityDtos(LocalDateTime start, LocalDateTime end) {
да, действительно...

2023-05-09 08:39 UTC, i2GR commented on src/test/java/ru/practicum/shareit/item/ItemResponseDtoMapperTest.java
> +    private Booking booking;
сконвертировано

2023-05-09 08:47 UTC, i2GR commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +    private final Long requestByUser2Id = 1L;
спасибо. исправлено.
не нужно плодить много Long-ов
но я оставил инициализации  ```private final Long user1Id = VALUE_ID_1;``` и ```private final Long requestByUser2Id = VALUE_ID_1;```
кажется так удобней читать

2023-05-09 20:09 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    throw new NotFoundException(format("item-request with id %d not found", requestId));
Только в местах, где еще логируешь что-то

2023-05-10 23:13 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        // Без StdDateFormat даты сериализуются в json так, что если последние милли/нано-секунды это нули(нуль), то это отбрасывается.
...

2023-05-10 23:16 UTC, i2GR commented on src/test/java/ru/practicum/shareit/item/ItemResponseDtoMapperTest.java
> +    private Booking booking;
BookingServiceImplTestWithMock.java не нужен - он дублирует BookingServiceImplTest.java
видимо издержки пуша-пула.
комментарий применен к  BookingServiceImplTest.java

2023-05-10 23:17 UTC, i2GR commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTestWithMock.java
> +    private BookingResponseDto response1Dto, response2Dto;
BookingServiceImplTestWithMock.java не нужен - он дублирует BookingServiceImplTest.java
видимо издержки пуша-пула.
комментарий применен к  BookingServiceImplTest.java

2023-05-11 11:03 UTC, AnastasiyaFomkina approved these changes

2023-05-11 16:01 UTC, i2GR commented
спасибо за ревью

2023-05-14 11:40 UTC, merged