Add docker
i2GR/java-shareit pull request #8
Opened 2023-05-19 22:04 UTC by i2GR

2023-05-20 22:51 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 🔥

2023-05-20 22:51 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +//@AllArgsConstructor
Нужно удалить закомментированный код

2023-05-21 10:41 UTC, i2GR commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +//@AllArgsConstructor
прошелся по коду,
удалил закомментированный код 
исправил незначительные опечатки и использование  локальных переменных

2023-05-21 13:21 UTC, AnastasiyaFomkina approved these changes

2023-09-01 21:11 UTC, merged